apiVersion: 1
groups:
  - orgId: 1
    name: environment-co2
    folder: Alerts
    interval: 1m
    rules:
      - uid: co2-warning-800
        title: CO2 Warning (>= 800 ppm)
        condition: A
        data:
          - refId: A
            datasourceUid: prometheus
            model:
              expr: "netatmo_co2_ppm >= 800"
              instant: false
              intervalMs: 60000
              maxDataPoints: 43200
        for: 5m
        annotations:
          summary: "CO2 levels >= 800 ppm"
        labels:
          severity: warning
      - uid: co2-danger-1000
        title: CO2 Danger (>= 1000 ppm)
        condition: A
        data:
          - refId: A
            datasourceUid: prometheus
            model:
              expr: "netatmo_co2_ppm >= 1000"
              instant: false
              intervalMs: 60000
              maxDataPoints: 43200
        for: 5m
        annotations:
          summary: "CO2 levels >= 1000 ppm"
        labels:
          severity: critical


